Added new features to script
-dhclient executed on-the-fly if no lease files detected
-can now handle
multiple DHCP hosts in the lease file, making it
compatible with
multi-NIC cloud environments

diff --git a/cloud-set-guest-password b/cloud-set-guest-password
--- a/cloud-set-guest-password
+++ b/cloud-set-guest-password
@@ -1,10 +1,11 @@
 #!/bin/bash
 #
 # Init file for Password Download Client
+## Ninefold Edited
 #
 # chkconfig: 345 98 02
 # description: Password Download Client
-
+#
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
 # distributed with this work for additional information
@@ -37,44 +38,57 @@ do
 	if [ -f $DHCP_FILE ]
 	then
 		file_count=$((file_count+1))
-		PASSWORD_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')
+		PASSWORD_SERVER_IP_ARRAY=( $(grep dhcp-server-identifier $DHCP_FILE | tail | awk '{print $NF}' | tr -d '\;') )
 
-		if [ -n "$PASSWORD_SERVER_IP" ]
+        if [ -z $PASSWORD_SERVER_IP_ARRAY ]; then
+			logger -t "cloud" "Could not find dhclient leases, Generating dhclient leases file"
+			cmd="dhclient"
+			$cmd
+			logger -t "cloud" "dhclient leases should now exist!"
+			PASSWORD_SERVER_IP_ARRAY=( $(grep dhcp-server-identifier $DHCP_FILE | tail | awk '{print $NF}' | tr -d '\;') )
+			logger -t "cloud" "found ${#PASSWORD_SERVER_IP_ARRAY[@]} DHCP hosts in $DHCP_FILE, querying them for passwords"
+	    fi
+
+		if [ -n $PASSWORD_SERVER_IP_ARRAY ]
 		then
-			logger -t "cloud" "Found password server IP $PASSWORD_SERVER_IP in $DHCP_FILE"
-			logger -t "cloud" "Sending request to password server at $PASSWORD_SERVER_IP"
-			password=$(wget -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $PASSWORD_SERVER_IP:8080)
-			password=$(echo $password | tr -d '\r')
+			logger -t "cloud" "found ${#PASSWORD_SERVER_IP_ARRAY[@]} DHCP hosts in $DHCP_FILE, querying them for passwords"
+			for i in "${PASSWORD_SERVER_IP_ARRAY[@]}"
+			do
+				logger -t "cloud" "Found password server IP $i in $DHCP_FILE"
+				logger -t "cloud" "Sending request to password server at $i"
+				password=$(wget -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $i:8080)
+				password=$(echo $password | tr -d '\r')
+				if [ $? -eq 0 ]
+				then
+					logger -t "cloud" "Got response from server at $i"
 
-			if [ $? -eq 0 ]
-			then
-				logger -t "cloud" "Got response from server at $PASSWORD_SERVER_IP"
-
-				case $password in
-				
-				"")					logger -t "cloud" "Password server at $PASSWORD_SERVER_IP did not have any password for the VM"
-									continue
-									;;
-				
-				"bad_request")		logger -t "cloud" "VM sent an invalid request to password server at $PASSWORD_SERVER_IP"
-									error_count=$((error_count+1))
-									continue
-									;;
-									
-				"saved_password") 	logger -t "cloud" "VM has already saved a password from the password server at $PASSWORD_SERVER_IP"
-									continue
-									;;
-									
-				*)					logger -t "cloud" "VM got a valid password from server at $PASSWORD_SERVER_IP"
-									password_received=1
-									break
-									;;
-									
-				esac
-			else
-				logger -t "cloud" "Failed to send request to password server at $PASSWORD_SERVER_IP"
-				error_count=$((error_count+1))
-			fi
+					case $password in
+					
+					"")					logger -t "cloud" "Password server at $i did not have any password for the VM"
+										continue
+										;;
+					
+					"bad_request")		logger -t "cloud" "VM sent an invalid request to password server at $i"
+										error_count=$((error_count+1))
+										continue
+										;;
+										
+					"saved_password") 	logger -t "cloud" "VM has already saved a password from the password server at $i"
+										continue
+										;;
+										
+					*)					logger -t "cloud" "VM got a valid password from server at $i"
+										password_received=1
+										PASSWORD_SERVER_IP=$i
+										break
+										;;
+										
+					esac
+				else
+					logger -t "cloud" "Failed to send request to password server at $i"
+					error_count=$((error_count+1))
+				fi
+			done
 		else
 			logger -t "cloud" "Could not find password server IP in $DHCP_FILE"
 			error_count=$((error_count+1))
@@ -113,4 +127,3 @@ fi
 logger -t "cloud" "Sending acknowledgment to password server at $PASSWORD_SERVER_IP"
 wget -t 3 -T 20 -O - --header "DomU_Request: saved_password" $PASSWORD_SERVER_IP:8080
 exit 0
-
